import Universality

set_option format.width 100

#print axioms Universality.affine_orbit_universality
#check @Universality.affine_orbit_universality
#print Universality.AffineOrbitRealization
#check @Universality.lagrangian_squareZero_orbit_universality
#print axioms Universality.lagrangian_squareZero_orbit_universality
#check @Universality.GateSystem.sectionToOrbit_isPullback
#check @Universality.GateSystem.sectionToCell_isPullback
#check @Universality.SquareZeroGeometry.maximalRankScheme_dimension
#check @Universality.SquareZeroGeometry.cellMorphism_isClosedImmersion
#print Universality.GlobalSymplectic.AlgebraicSymplecticAtlas
#check @Universality.GlobalSymplectic.cell_pullback_form_zero
